// internal/metrics/tools/gen_metrics/main.go
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"gopkg.in/yaml.v3"
)

// ========== 数据结构 ==========

type MetricConfig struct {
	ServiceName string      `yaml:"service_name"`
	Subsystems  []Subsystem `yaml:"subsystems"`
}

type Subsystem struct {
	Name       string      `yaml:"name"`
	Counters   []Metric    `yaml:"counters"`
	Gauges     []Metric    `yaml:"gauges"`
	Histograms []Histogram `yaml:"histograms"`
}

type Metric struct {
	Name    string   `yaml:"name"`
	Help    string   `yaml:"help"`
	Labels  []string `yaml:"labels"`
	Methods []string `yaml:"methods"`
}

type Histogram struct {
	Metric
	Buckets []float64 `yaml:"buckets"`
}

// ========== 辅助函数 ==========

func toPascal(s string) string {
	parts := strings.Split(s, "_")
	for i, part := range parts {
		if len(part) > 0 {
			parts[i] = strings.ToUpper(part[:1]) + part[1:]
		}
	}
	return strings.Join(parts, "")
}

func hasMethod(methods []string, target string) bool {
	for _, m := range methods {
		if m == target {
			return true
		}
	}
	return false
}

func joinLabels(labels []string) string {
	if len(labels) == 0 {
		return ""
	}
	return strings.Join(labels, ", ")
}

func labelParams(labels []string) string {
	if len(labels) == 0 {
		return ""
	}
	params := make([]string, len(labels))
	for i, label := range labels {
		params[i] = label + " string"
	}
	return strings.Join(params, ", ")
}

func labelArgs(labels []string) string {
	if len(labels) == 0 {
		return ""
	}
	return strings.Join(labels, ", ")
}

// ========== 模板 ==========

const templateText = `// Code generated by go generate; DO NOT EDIT.
package metrics

import (
    "github.com/zeromicro/go-zero/core/metric"
    "user/internal/config"
)

// ========== Builder ==========

type builder struct {
    namespace string
    subsystem string
}

func newBuilder(c config.Config, subsystem string) *builder {
    return &builder{
        namespace: c.Name,
        subsystem: subsystem,
    }
}

func (b *builder) newCounterVec(name, help string, labels []string) metric.CounterVec {
    return metric.NewCounterVec(&metric.CounterVecOpts{
        Namespace: b.namespace,
        Subsystem: b.subsystem,
        Name:      name,
        Help:      help,
        Labels:    labels,
    })
}

func (b *builder) newGaugeVec(name, help string, labels []string) metric.GaugeVec {
    return metric.NewGaugeVec(&metric.GaugeVecOpts{
        Namespace: b.namespace,
        Subsystem: b.subsystem,
        Name:      name,
        Help:      help,
        Labels:    labels,
    })
}

func (b *builder) newHistogramVec(name, help string, buckets []float64, labels []string) metric.HistogramVec {
    return metric.NewHistogramVec(&metric.HistogramVecOpts{
        Namespace: b.namespace,
        Subsystem: b.subsystem,
        Name:      name,
        Help:      help,
        Buckets:   buckets,
        Labels:    labels,
    })
}

{{- range .Subsystems }}
// ========== Subsystem: {{ .Name }} ==========

type {{ .Name | toPascal }}Metrics struct {
    {{- range .Counters }}
    {{ .Name | toPascal }} *SafeCounter{{ if .Labels }}_{{ .Name | toPascal }}{{ end }}
    {{- end }}
    {{- range .Gauges }}
    {{ .Name | toPascal }} *SafeGauge{{ if .Labels }}_{{ .Name | toPascal }}{{ end }}
    {{- end }}
    {{- range .Histograms }}
    {{ .Name | toPascal }} *SafeHistogram{{ if .Labels }}_{{ .Name | toPascal }}{{ end }}
    {{- end }}
}

func new{{ .Name | toPascal }}Metrics(c config.Config) *{{ .Name | toPascal }}Metrics {
    b := newBuilder(c, "{{ .Name }}")
    m := &{{ .Name | toPascal }}Metrics{}

    {{- range .Counters }}
    m.{{ .Name | toPascal }} = &SafeCounter{{ if .Labels }}_{{ .Name | toPascal }}{{ end }}{
        CounterVec: b.newCounterVec("{{ .Name }}", "{{ .Help }}", {{ printf "%#v" .Labels }}),
    }
    {{- end }}
    {{- range .Gauges }}
    m.{{ .Name | toPascal }} = &SafeGauge{{ if .Labels }}_{{ .Name | toPascal }}{{ end }}{
        GaugeVec: b.newGaugeVec("{{ .Name }}", "{{ .Help }}", {{ printf "%#v" .Labels }}),
    }
    {{- end }}
    {{- range .Histograms }}
    m.{{ .Name | toPascal }} = &SafeHistogram{{ if .Labels }}_{{ .Name | toPascal }}{{ end }}{
        HistogramVec: b.newHistogramVec("{{ .Name }}", "{{ .Help }}", {{ printf "%#v" .Buckets }}, {{ printf "%#v" .Labels }}),
    }
    {{- end }}

    return m
}
{{- end }}

{{- range .Subsystems }}
{{- range .Counters }}
// ========== SafeCounter for {{ .Name }} ==========

type SafeCounter{{ if .Labels }}_{{ .Name | toPascal }}{{ end }} struct {
    metric.CounterVec
}

{{- if hasMethod .Methods "inc" }}
// Inc increments the counter with the given labels.
func (c *SafeCounter{{ if .Labels }}_{{ .Name | toPascal }}{{ end }}) Inc({{ labelParams .Labels }}) {
    c.CounterVec.Inc({{ labelArgs .Labels }})
}
{{- end }}

{{- if hasMethod .Methods "add" }}
// Add adds the given value to the counter.
func (c *SafeCounter{{ if .Labels }}_{{ .Name | toPascal }}{{ end }}) Add(v float64, {{ labelParams .Labels }}) {
    c.CounterVec.Add(v, {{ labelArgs .Labels }})
}
{{- end }}
{{- end }}

{{- range .Gauges }}
// ========== SafeGauge for {{ .Name }} ==========

type SafeGauge{{ if .Labels }}_{{ .Name | toPascal }}{{ end }} struct {
    metric.GaugeVec
}

{{- if hasMethod .Methods "set" }}
// Set sets the gauge value.
func (g *SafeGauge{{ if .Labels }}_{{ .Name | toPascal }}{{ end }}) Set(v float64, {{ labelParams .Labels }}) {
    g.GaugeVec.Set(v, {{ labelArgs .Labels }})
}
{{- end }}

{{- if hasMethod .Methods "inc" }}
// Inc increments the gauge by 1.
func (g *SafeGauge{{ if .Labels }}_{{ .Name | toPascal }}{{ end }}) Inc({{ labelParams .Labels }}) {
    g.GaugeVec.Inc({{ labelArgs .Labels }})
}
{{- end }}

{{- if hasMethod .Methods "dec" }}
// Dec decrements the gauge by 1.
func (g *SafeGauge{{ if .Labels }}_{{ .Name | toPascal }}{{ end }}) Dec({{ labelParams .Labels }}) {
    g.GaugeVec.Dec({{ labelArgs .Labels }})
}
{{- end }}
{{- end }}

{{- range .Histograms }}
// ========== SafeHistogram for {{ .Name }} ==========

type SafeHistogram{{ if .Labels }}_{{ .Name | toPascal }}{{ end }} struct {
    metric.HistogramVec
}

{{- if hasMethod .Methods "observe" }}
// Observe records the observed value.
func (h *SafeHistogram{{ if .Labels }}_{{ .Name | toPascal }}{{ end }}) Observe(v float64, {{ labelParams .Labels }}) {
    h.HistogramVec.Observe(v, {{ labelArgs .Labels }})
}
{{- end }}
{{- end }}
{{- end }}

// ========== MetricsManager ==========

type MetricsManager struct {
    {{- range .Subsystems }}
    {{ .Name | toPascal }} *{{ .Name | toPascal }}Metrics
    {{- end }}
}

// NewMetricsManager creates a new metrics manager.
func NewMetricsManager(c config.Config) *MetricsManager {
    return &MetricsManager{
        {{- range .Subsystems }}
        {{ .Name | toPascal }}: new{{ .Name | toPascal }}Metrics(c),
        {{- end }}
    }
}
`

// ========== 主函数 ==========

func main() {
	// 读取 YAML 文件
	data, err := os.ReadFile("internal/metrics/definition.yaml")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading definition.yaml: %v\n", err)
		os.Exit(1)
	}

	var config MetricConfig
	if err := yaml.Unmarshal(data, &config); err != nil {
		fmt.Fprintf(os.Stderr, "Error parsing YAML: %v\n", err)
		os.Exit(1)
	}

	// 准备模板函数
	funcMap := template.FuncMap{
		"toPascal":    toPascal,
		"hasMethod":   hasMethod,
		"labelParams": labelParams,
		"labelArgs":   labelArgs,
		"joinLabels":  joinLabels,
	}

	tmpl, err := template.New("metrics").Funcs(funcMap).Parse(templateText)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error parsing template: %v\n", err)
		os.Exit(1)
	}

	// 执行模板
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, config); err != nil {
		fmt.Fprintf(os.Stderr, "Error executing template: %v\n", err)
		os.Exit(1)
	}

	// 格式化代码
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error formatting code: %v\n", err)
		fmt.Fprintf(os.Stderr, "Raw output:\n%s\n", buf.String())
		os.Exit(1)
	}

	// 写入文件
	outputPath := filepath.Join("internal", "metrics", "metrics_gen.go")
	if err := os.WriteFile(outputPath, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing file: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("Generated internal/metrics/metrics_gen.go")
}
